config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :users
  resources :users, only: :show
  resources :posts, only: :index
  resources :reviews, only: [:index, :show, :new, :create, :destroy]
  resources :searches,only: :index
  resources :articles, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    {id: 0, name: '選択してください'},
    {id: 1, name: '赤'}, {id: 2, name: '白'}, {id: 3, name: 'ロゼ'},
    {id: 4, name: 'スパークリング'}, {id: 5, name: 'デザート'},
  ]
end

app/models/review.rb
class Review < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  mount_uploader :image, ImageUploader
  validates :name, presence: true
  belongs_to :user
  def self.search(search)
    return Review.all unless search
    Review.where(['name LIKE ?', "%#{search}%"])
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  require 'mechanize'
  def index
    agent = Mechanize.new
    page = agent.get("https://www.winekingdom.co.jp/_tags/%E3%83%8B%E3%83%A5%E3%83%BC%E3%82%B9")
    @elements = page.search('a.content-link')
    @images = page.search('div.content-leading.flex-item a img')
    sleep(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def index
  end

  def show
  
    a = params[:category_id]
    case a
    when "1"
      @reviews = Review.where(category_id: 1)
    when "2"
      @reviews = Review.where(category_id: 2)
    when "3"
      @reviews = Review.where(category_id: 3)
    when "4"
      @reviews = Review.where(category_id: 4)
    when "5"
      @reviews = Review.where(category_id: 5)
    end
  end

  def new
    @review = Review.new
  end

  def create
    Review.create(review_params)
    redirect_to root_path
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to "/users/#{current_user.id}"
  end

  private
  def review_params
    params.require(:review).permit(:name, :text, :category_id, :image, :rate).merge(user_id: current_user.id)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
    @reviews = Review.search(params[:search]).limit(132)
    @search = params[:search]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @nickname = current_user.nickname
    @reviews = current_user.reviews
    
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.erb
<div class="article-logo">
  ワインに関するニュースをお届け
</div>
<div class="article_box">
  <% @elements.each do|element| %>
      <div class="article_content">
        <%=link_to(element.inner_text, element[:href])%>
      </div>
  <%end%>
  <% @images.each do |image|%>
      <div class="article_image-box">
        <%=image_tag image.get_attribute('src'), class: "article_image"%>
      </div>
  <% end %>
</div>

app/views/categorys/index.html.erb
<div class="wine_category_up">
  <div class="red">
  <div class="wine_logo">赤</div>
    <%= link_to "/reviews/show/", controller: "reviews", action: "show", a: 1 do %>
      <%= image_tag "mywine_y-7772276.jpeg", class: "wine_image" %>
    <% end %>
  </div>
  <div class="white">
  <div class="wine_logo">白</div>
    <%= link_to "/reviews/show/", controller: "reviews", action: "show", a: "2" do %>
      <%= image_tag "img56678590.jpg", class: "wine_image" %>
    <% end %>
  </div>
  <div class="roze">
  <div class="wine_logo">ロゼ</div>
   <%= link_to "/reviews/show/", controller: "reviews", action: "show", a: "3" do %>
      <%= image_tag "Sancerre_rose_Wine.jpg", class: "wine_image" %>
    <% end %>
    </div>
</div>
<div class="wine_category_down">
  <div class="spark">
  <div class="wine_logo">スパークリング</div>
    <%= link_to "/reviews/show/", controller: "reviews", action: "show", a: "4" do %>
      <%= image_tag "719471_615.jpg", class: "wine_image" %>
    <% end %>
  </div>
  <div class="desert">
  <div class="wine_logo">デザート</div>
    <%= link_to "/reviews/show/", controller: "reviews", action: "show", a: "5" do %>
      <%= image_tag "cee0164bd39252b82ffc29cab59f2001fd1ac655.jpg", class: "wine_image" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WineReviewers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <div class="nav">
        <%= link_to "Wine::Reviewers", root_path, class: "nav-logo" %>
      </div>
      <% if user_signed_in? %>
        <%= form_with url: searches_path, local: true, method: :get, class: "search-review" do |f| %>
          <%= f.text_field :search, placeholder: "ワイン名で探す" %>
          <%= f.submit 'Search' %>
        <% end %>
      <% end %>
      <div class="nav-items">
       <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "header__right--btn" %>
        <% else %>
          <%= link_to "LogIn", new_user_session_path, class: "header__right--btn" %>
          <%= link_to "SignUp", new_user_registration_path, class: "header__right--btn" %>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to "Mypage", user_path(current_user.id), class: "nav-button" %>
        <% end%>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="contents">
  <div class="main-view">
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="main-logo">主に無色に近い色調から（時に緑色がかった）黄色みを帯びたワインを白ワインと呼ぶ。白ブドウなど主に色の薄い果皮のブドウを原料とし、発酵には果汁のみを使用する。酸味の強い物は、一般的に魚料理に合うとされる。白ワインは、料理と合わせる辛口からデザートワインにする極甘口まで甘さに幅がある。なお、フランス東部のジュラ地方にはヴァン・ジョーヌ（仏: Vin jaune、黄ワイン）という特殊な白ワインがある</div>
            <%= image_tag "wine-1761613_1280.webp", class: 'd-block w-100', :size =>'1450x500' %>
        </div>
        <div class="carousel-item">
          <div class="main-logo">透き通った赤や濃い紫、あるいは赤褐色のワインを赤ワインと呼ぶ。一般に白ワインよりも渋みの成分であるタンニンを多く含み長期保存が可能である。主として黒ブドウや赤ブドウを原料とし、果実を丸ごとアルコール発酵させる。この発酵の過程で、果皮に含まれる色素やタンニンが抽出される。マロラクティック発酵により減酸が行われることも多い。濃厚な風味のものは一般的に肉料理に合うとされる。また冷やすと香りの成分が揮発しにくくなったり苦味が増すので、冷やさないのが普通である。一般的に赤ワインには辛口しかなく、コクとタンニンにより、ライトボディーからフルボディーといった分類がなされる。</div>
            <%= image_tag "grapes-2104077_1280.jpg", class: 'd-block w-100', :size =>'1450x500' %>
        </div>
        <div class="carousel-item">
          <div class="main-logo">ロゼ (rosé) とはフランス語で「ピンク色」を意味し、時にピンク・ワインとも呼ばれる赤みを帯びた淡い色調のワインを指す。製法には、果皮の色の薄いブドウを赤ワインのように醸造する方法や、赤ワインと同じブドウを白ワインのように醸造する方法、赤と白の双方のブドウによる混醸、赤ワインの醸造途上で色の素である果皮を取り除く、などがあり、味わいも様々である。中には赤ワインと白ワインを混合したものや白ワインに着色しただけの製品もある。</div>
            <%= image_tag "tuscany-4664883_1280.jpg", class: 'd-block w-100', :size =>'1450x500' %>
        </div>
      </div>
    </div>
  </div>
  <div class="main-content">
    <div class="content-list">
      <div class="content-box">
        <div class="review-box">
          <%= image_tag "★IMG_8169.jpg", class: 'rounded-circle', :size =>'200x200'%>
        </div>
        <%= link_to "WineReview", new_review_path, class: "review-logo" %>  
        <div class="memo1">Review your favorite wine. Your review can be shared with everyone in the world.</div>
      </div>
    </div>
    <div class="content-list">
      <div class="content-box">
        <div class="review-box">
          <%= image_tag "wine-3503895_1280.jpg", class: 'rounded-circle', :size =>'200x200'%>
        </div>
        <%= link_to "Category", reviews_path, class: "review-logo" %> 
        <div class="memo1">You can see the wines reviewed by everyone in the world by type.</div>
      </div>
    </div>
    <div class="content-list">
      <div class="content-box">
        <div class="review-box">
          <%= image_tag "bottle-791699_1280.jpg", class: 'rounded-circle', :size =>'200x200'%>
        </div>
        <%= link_to "News", articles_path, class: "review-logo" %>
        <div class="memo1">We bring you news about wines from around the world.</div>
      </div>
  </div>
</div>
<div class="footer">
  <p>© All rights reserved by WineReviewers</p>
<div>

app/views/reviews/index.html.erb
<div class="wine_category_up">
  <div class="red">
  <div class="wine_logo">赤</div>
    <%= link_to review_path(id: 1, category_id: 1), controller: "reviews", action: "show" do %>
      <%= image_tag "mywine_y-7772276.jpeg", class: "wine_image" %>
    <% end %>
  </div>
  <div class="white">
  <div class="wine_logo">白</div>
    <%= link_to review_path(id: 2, category_id: 2), controller: "reviews", action: "show" do %>
      <%= image_tag "img56678590.jpg", class: "wine_image" %>
    <% end %>
  </div>
  <div class="roze">
  <div class="wine_logo">ロゼ</div>
   <%= link_to review_path(id: 3, category_id: 3), controller: "reviews", action: "show" do %>
      <%= image_tag "Sancerre_rose_Wine.jpg", class: "wine_image" %>
    <% end %>
    </div>
</div>
<div class="wine_category_down">
  <div class="spark">
  <div class="wine_logo">スパークリング</div>
    <%= link_to review_path(id: 4, category_id: 4), controller: "reviews", action: "show" do %>
      <%= image_tag "719471_615.jpg", class: "wine_image" %>
    <% end %>
  </div>
  <div class="desert">
  <div class="wine_logo">デザート</div>
    <%= link_to review_path(id: 5, category_id: 5), controller: "reviews", action: "show" do %>
      <%= image_tag "cee0164bd39252b82ffc29cab59f2001fd1ac655.jpg", class: "wine_image" %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <%= form_with(model: @review, local: true) do |form| %>
  <div class="review-input">
    <%= form.text_area :text, class: 'review-form',placeholder: "Review" , rows: "10" %>  
  </div>
  <div class="form-multi">
    <%= form.text_field :name, class: 'name-form', placeholder: "Name" %>
    <%= form.collection_select :category_id, Category.all, :id, :name %>
    <div class="form_mask">
      <%= form.label :image, class: 'form-mask__image' do %>
        <i class="fas fa-wine-bottle"></i>
        <%= form.file_field :image, class: 'image-form' %>
      <% end %>
    </div>
    <div class="form-group row" id="star">
      <%= form.label :rate,'評価 ', class:'col-md-3 col-form-label' %>
      <%= form.hidden_field :rate, id: :review_star %>
    </div>
      <script>
      $('#star').raty({
        size     : 36,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'review[rate]',
        half: true,
      });
      </script>  

    <%= form.submit "SEND", class: 'submit-btn'%>
  </div>
  <% end %>
</div>

app/views/reviews/show.html.erb
<div class="contents-post">
  <div class="content-index">
    <% if @reviews %>
      <% @reviews.each do |review| %>
        <div class="content__box" >
          <div class="content__box-text">
            <div class="name"><%= review.name %></div>
            <%= link_to  do %>
            <strong><%= review.user.nickname %>さんのレビュー</strong>
            <% end %>
            <div class="point">評価：<%= review.rate %>点</div>
            <div id="star-rate-<%= review.id %>"></div>
            <script>
            $('#star-rate-<%= review.id %>').raty({
              size: 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= review.rate %>,
            });
            </script> 
            <%= simple_format(review.text) %>
          </div>
          <div class="content__box-image">
            <% if review.image? %>
              <%= image_tag review.image.url %>
            <% else %>
              <%= image_tag "unnamed.jpg", :size =>'200x200'%>
            <% end %>
          </div>
          </div>  
        <% end %>
    <% end %>
  </div>
</div>

app/views/searches/index.html.erb
<div class="contents-post">
  <div class="contents-logo">
    検索結果のレビュー一覧
  </div>
  <div class="content-index">
    <% @reviews.each do |review| %>
      <div class="content__box" >
          <div class="content__box-text">
            <div class="name"><%= review.name %></div>
              <%= review.category.name %>
            <div class="point">評価：<%= review.rate %>点</div>
            <div id="star-rate-<%= review.id %>"></div>
            <script>
            $('#star-rate-<%= review.id %>').raty({
              size: 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= review.rate %>,
            });
            </script> 
            <div class="box-text">
              <%= simple_format(review.text) %>
          </div>
          <div class="d-btn"><%= link_to '削除', "/reviews/#{review.id}", method: :delete %></div>
        </div>
        <div class="content__box-image">
          <% if review.image? %>
            <%= image_tag review.image.url %>
          <% else %>
            <%= image_tag "unnamed.jpg", :size =>'200x200'%>
          <% end %>
        </div>
        
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents-post">
  <div class="contents-logo">
    <%= @nickname %>さんのレビュー一覧
  </div>
  <div class="content-index">
    <% @reviews.each do |review| %>
      <div class="content__box" >
          <div class="content__box-text">
            <div class="name"><%= review.name %></div>
              <%= review.category.name %>
            <div class="point">評価：<%= review.rate %>点</div>
            <div id="star-rate-<%= review.id %>"></div>
            <script>
            $('#star-rate-<%= review.id %>').raty({
              size: 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= review.rate %>,
            });
            </script> 
            <div class="box-text">
              <%= simple_format(review.text) %>
          </div>
          <div class="d-btn"><%= link_to '削除', "/reviews/#{review.id}", method: :delete %></div>
        </div>
        <div class="content__box-image">
          <% if review.image? %>
            <%= image_tag review.image.url %>
          <% else %>
            <%= image_tag "unnamed.jpg", :size =>'200x200'%>
          <% end %>
        </div>
        
      </div>
    <% end %>
  </div>
</div>